Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis
x:real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


escreval("Digite um número, este algoritimo mostrará o numero anterior a ele:")
leia(x)
resultado <- x-1
escreval(resultado)


Fimalgoritmo