algoritmo "semnome"
// Função : Armazenar 10 em A e 20 em B,
// troca os valores de A por B e mostra
// na tela o final
// Autor : Cainã
// Data : 07/03/2022
// Seção de Declarações 
var
a:inteiro
b:inteiro
c:inteiro


inicio
// Seção de Comandos 
a <- 10
b <- 20
c <- a
a <- b
b <- c
escreval ("***************************")
escreval ("o valor de A agora é:", a)
escreval ("o valor de B agora é:", b)
escreval ("***************************")

fimalgoritmo
