algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
qtdemin:real
qtdemax:real
estoquemed:real
inicio
// dados de entrada
escreval ("digite o valor da qtde minima:")
leia(qtdemin)
escreval ("digite o valor da qtde maxima:")
leia(qtdemax)
//processamento
estoquemed<-(qtdemin+qtdemax)/2
//dados de saida
escreval("o estoque medio é: ", estoquemed)

fimalgoritmo
